import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("jvm") version "2.4.0"
    kotlin("plugin.serialization") version "2.4.0"
    id("org.jetbrains.dokka") version "2.2.0"
    id("com.vanniktech.maven.publish") version "0.37.0"
}

group = "org.lettras.artificialss"
version = "0.2.1"

dependencies {
    // WebAssembly runtime written in pure Java: no native code, runs on any JVM and on Android.
    implementation("com.dylibso.chicory:runtime:1.7.5")
    implementation("com.dylibso.chicory:wasm:1.7.5")
    // Compiles the engine to JVM bytecode on first use (much faster than interpreting). Not usable on Android.
    implementation("com.dylibso.chicory:compiler:1.7.5")
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")

    testImplementation(kotlin("test"))
}

kotlin {
    jvmToolchain(17)
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11) // Android and older JVMs
        allWarningsAsErrors.set(true)
        explicitApi()
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Parity fixtures are shared with the MCP server: generated by the npm package, the reference behaviour.
sourceSets.test { resources.srcDir("../mcp/tests/fixtures") }

tasks.test {
    useJUnitPlatform()
    testLogging { events("passed", "failed", "skipped"); showStandardStreams = false }
}

// Maven Central (Central Portal). Uploading is manual-release: the bundle waits in the portal until you press Publish.
// Credentials and the signing key come from environment variables, never from this file; see ../docs/MAVEN_CENTRAL.md.
mavenPublishing {
    publishToMavenCentral(automaticRelease = false)
    if (providers.gradleProperty("signingInMemoryKey").isPresent) signAllPublications()

    coordinates("org.lettras.artificialss", "lettras", version.toString())

    pom {
        name.set("Lettras")
        description.set("Word-search generator for es, en, pt, fr, de and it with native accented letters. Runs locally on the JVM and Android.")
        inceptionYear.set("2026")
        url.set("https://github.com/Artificialss/lettras-sdk")
        licenses {
            license {
                name.set("MIT License (library code)")
                url.set("https://github.com/Artificialss/lettras-sdk/blob/main/LICENSE")
                distribution.set("repo")
            }
            license {
                name.set("Lettras Engine License (bundled compiled engine, proprietary)")
                url.set("https://github.com/Artificialss/lettras-sdk/blob/main/kotlin/src/main/resources/org/lettras/LICENSE-ENGINE")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("artificialss")
                name.set("Artificialss")
                url.set("https://artificialss.ai")
            }
        }
        scm {
            url.set("https://github.com/Artificialss/lettras-sdk")
            connection.set("scm:git:git://github.com/Artificialss/lettras-sdk.git")
            developerConnection.set("scm:git:ssh://git@github.com/Artificialss/lettras-sdk.git")
        }
    }
}
