import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("jvm") version "2.4.0"
    kotlin("plugin.serialization") version "2.4.0"
    `maven-publish`
}

group = "org.lettras"
version = "0.1.0"

dependencies {
    // WebAssembly runtime written in pure Java: no native code, runs on any JVM and on Android.
    implementation("com.dylibso.chicory:runtime:1.7.5")
    implementation("com.dylibso.chicory:wasm:1.7.5")
    // Compiles the engine to JVM bytecode on first use (much faster than interpreting). Not usable on Android.
    implementation("com.dylibso.chicory:compiler:1.7.5")
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")

    testImplementation(kotlin("test"))
}

kotlin {
    jvmToolchain(17)
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11) // Android and older JVMs
        allWarningsAsErrors.set(true)
        explicitApi()
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Parity fixtures are shared with the MCP server: generated by the npm package, the reference behaviour.
sourceSets.test { resources.srcDir("../mcp/tests/fixtures") }

tasks.test {
    useJUnitPlatform()
    testLogging { events("passed", "failed", "skipped"); showStandardStreams = false }
}

publishing {
    publications {
        create<MavenPublication>("lettras") {
            from(components["java"])
            pom {
                name.set("Lettras")
                description.set("Word-search generator for es, en, pt, fr, de and it with native accented letters.")
                url.set("https://github.com/Artificialss/lettras-sdk")
                licenses {
                    license {
                        name.set("MIT (code); the bundled engine binary is proprietary, see LICENSE-ENGINE")
                        url.set("https://github.com/Artificialss/lettras-sdk/blob/main/LICENSE")
                    }
                }
            }
        }
    }
}
